<a href="https://colab.research.google.com/github/vijeta-chaudhary/Daily-Coding-Problem-Solutions/blob/master/stats_assi_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
#1 . Write a Pandas program to create and display a one-dimensional array-like object containing an array of data using Pandas module.

a=pd.array([1,2,3,4,5,6,4,7,8,9])
a

<IntegerArray>
[1, 2, 3, 4, 5, 6, 4, 7, 8, 9]
Length: 10, dtype: Int64

In [ ]:
#2. Write a Pandas program to convert a Panda module Series to Python list and it's type.
a1=pd.Series([1,2,3,4,5,6,5,6,7,8,9])
a2 = a1.tolist()
a2

[1, 2, 3, 4, 5, 6, 5, 6, 7, 8, 9]

In [ ]:
#3. Write a Pandas program to add, subtract, multiple and divide two Pandas Series.
# Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]
a1 = pd.Series([2, 4, 6, 8, 10])
a2 = pd.Series([1, 3, 5, 7, 9])

add = a1 + a2
print(add)

subs = a1 - a2
print(subs)

mul= a1*a2
print(mul)

div= a1/a2
print(div)

0     3
1     7
2    11
3    15
4    19
dtype: int64
0    1
1    1
2    1
3    1
4    1
dtype: int64
0     2
1    12
2    30
3    56
4    90
dtype: int64
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


In [ ]:
#4. Write a Pandas program to compare the elements of the two Pandas Series.
#Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 10]

a1 =pd.Series([2, 4, 6, 8, 10])
a2 =pd.Series([1, 3, 5, 7, 10])


eq = a1 == a2
ge = a1 > a2
le = a1 < a2

print(eq)
print(ge)
print(le)


0    False
1    False
2    False
3    False
4     True
dtype: bool
0     True
1     True
2     True
3     True
4    False
dtype: bool
0    False
1    False
2    False
3    False
4    False
dtype: bool


In [ ]:
#5. Write a Pandas program to convert a dictionary to a Pandas series.


dict1 = {'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
ser1 = pd.Series(dict1)
print(ser1)

a    100
b    200
c    300
d    400
e    800
dtype: int64


In [ ]:
#6. Write a Pandas program to convert a NumPy array to a Pandas series.
a= np.array([10,20,30,40,50])
b= pd.Series(a)
b

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
#7. Write a Pandas program to change the data type of given a column or a Series.

aa = pd.Series(['100', '200', 'python', '300.12', '400'])

bb = pd.to_numeric(aa, errors='coerce')
print(bb)

0    100.00
1    200.00
2       NaN
3    300.12
4    400.00
dtype: float64


In [ ]:
#8. Write a Pandas program to convert the first column of a DataFrame as a Series.

a1=pd.DataFrame( {'col1': [1, 2, 3, 4, 7, 11],
                  'col2': [4, 5, 6, 9, 5, 0],
                  'col3': [7, 5, 8, 12, 1, 11]})

s1 = a1['col3']
s2 = pd.Series(s1)
print(s2)

0     7
1     5
2     8
3    12
4     1
5    11
Name: col3, dtype: int64


In [ ]:
#9. Write a Pandas program to convert a given Series to an array.
ser = pd.Series([100,200,'python',300,12,400])

arr= pd.array(ser)

print(arr)

<class 'pandas.core.arrays.numpy_.PandasArray'>


In [ ]:
#10. Write a Pandas program to convert a Series of lists to one Series.

ser2 = pd.Series([['Red', 'Green', 'White'],['Red','Black'], ['Yellow']])

ser3 = ser2.explode()
ser3.reset_index(drop=True)

0       Red
1     Green
2     White
3       Red
4     Black
5    Yellow
dtype: object

In [ ]:
#11. Write a Pandas program to sort a given Series.
ab = pd.Series([100, 200, 'python', 300.12, 400])
ab1 = ab.sort_values
print(ab1)

<bound method Series.sort_values of 0       100
1       200
2    python
3    300.12
4       400
dtype: object>


In [ ]:
#12. Write a Pandas program to add some data to an existing Series.
ser1 = pd.Series([10,20,'python',30,40,50])
ser2 = pd.Series([60,70,80,90,'php'])

ser3 = ser1.append(ser2)
ser3


<ipython-input-53-53f4b38fc840>:5: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ser3 = ser1.append(ser2)


0        10
1        20
2    python
3        30
4        40
5        50
0        60
1        70
2        80
3        90
4       php
dtype: object

In [ ]:
#13.  Write a Pandas program to create a subset of a given series based on value and condition.

s= pd.Series([0,1,2,3,4,5,6,7,8,9,10])

t = s<6

s2=s[t]
s2

0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64

In [ ]:
#14. Write a Pandas program to change the order of index of a given series.
a =  pd.Series([10, 20, 30, 40, 50], index=['a', 'b', 'c', 'd', 'e'])
new = ['b','a','c','d','e']
rein = a.reindex(new)
rein

b    20
a    10
c    30
d    40
e    50
dtype: int64

In [ ]:
#15. Write a Pandas program to create the mean and standard deviation of the data of a given Series.
a = pd.Series([1,2,3,4,5,6,7,8,9,5,3])

mean= a.mean()
sd = a.std()

print('mean is :',round(mean,3))
print('std deviation is :',round(sd,3))


mean is : 4.818
std deviation is : 2.523


In [ ]:
#16. Write a Pandas program to get the items of a given series not present in another given series.
ser1=pd.Series([1,2,3,4,5,6,7,8,9,10])
ser2=pd.Series([2,4,6,8,10])

ser3 = np.setdiff1d(ser1,ser2)
ser3


array([1, 3, 5, 7, 9])

In [ ]:
#17. Write a Pandas program to get the items which are not common of two given series.
ser1=pd.Series([1,2,3,4,5,6,7,8,9,10])
ser2=pd.Series([2,4,6,8,10])

ser3 = np.setdiff1d(ser1,ser2)
ser3


array([1, 3, 5, 7, 9])

In [ ]:
#18. Write a Pandas program to compute the minimum, 25th percentile, median, 75th, and maximum of a given series.

ser = pd.Series(np.random.rand(20) * 10)
result = ser.describe(percentiles=[0.25, 0.5, 0.75])
final = result[['min', '25%', '50%', '75%', 'max']]
print(final)

min    0.156418
25%    1.407345
50%    4.531065
75%    7.864528
max    9.501490
dtype: float64


In [ ]:
#19. Write a Pandas program to calculate the frequency counts of each unique value of a given series.
s1 = pd.Series([1,7,1,6,9,1])
s1.value_counts()

1    3
7    1
6    1
9    1
dtype: int64

In [ ]:
#20. Write a Pandas program to display the most frequent value in a given series and replace everything else as 'Other' in the series.

s = pd.Series([3,1,1,3,2,2,1,2,3,1,2,2,2,3,3])
freq = s.mode().iloc[0]
new = s.where(s == freq, 'Other')
print(new)

0     Other
1     Other
2     Other
3     Other
4         2
5         2
6     Other
7         2
8     Other
9     Other
10        2
11        2
12        2
13    Other
14    Other
dtype: object


In [ ]:
#21. Write a Pandas program to find the positions of numbers that are multiples of 5 of a given series.
ser=pd.Series([1,9,8,6,9,7,1,1,1])
pos= ser[ser % 5 == 0].index
pos

Int64Index([], dtype='int64')

In [ ]:
#22. Write a Pandas program to extract items at given positions of a given series.

rn = pd.Series(np.random.randint(1,100,20))
print(rn)
ex= [2,4,6,8,10]
rn.iloc[ex]

0     35
1      2
2     49
3     59
4     40
5     44
6      7
7     12
8     18
9     56
10    49
11    73
12    97
13    38
14    20
15    43
16    67
17    32
18    81
19    53
dtype: int64


2     49
4     40
6      7
8     18
10    49
dtype: int64

In [ ]:
#23. Write a Pandas program to get the positions of items of a given series in another given series.
ser1=pd.Series([1,2,3,4,5,6,7,8,9,10])
ser2=pd.Series([1,3,5,7,10])

pos=np.where(ser1.isin(ser2))
pos

(array([0, 2, 4, 6, 9]),)

In [ ]:
#24. Write a Pandas program to convert the first and last character of each word to uppercase in each word of a given series.
old = pd.Series(['php','python','java','c#'])

new = old.apply(lambda word: word[0].upper() + word[1:-1] + word[-1].upper())
new

0       PhP
1    PythoN
2      JavA
3        C#
dtype: object

In [ ]:
#25. Write a Pandas program to calculate the number of characters in each word in a given series.
ser = pd.Series(['php','python','java','c#'])

count = ser.apply(lambda word : len(word))
count

0    3
1    6
2    4
3    2
dtype: int64

In [ ]:
#26. Write a Pandas program to compute the difference of differences between consecutive numbers of a given series.

ser2 = pd.Series([1, 3, 5, 8, 10, 11, 15])
diff = ser2.diff()
print(diff)
diff_of_diff = diff.diff()
print(diff_of_diff)

0    NaN
1    2.0
2    2.0
3    3.0
4    2.0
5    1.0
6    4.0
dtype: float64
0    NaN
1    NaN
2    0.0
3    1.0
4   -1.0
5   -1.0
6    3.0
dtype: float64


In [ ]:
#27. Write a Pandas program to convert a series of date strings to a timeseries.

ser1 = pd.Series(['01 Jan 2015', '10-02-2016', '20180307', '2014/05/06', '2016-04-12', '2019-04-06T11:20'])
time_ser = pd.to_datetime(ser1, format= '%d %b %Y %H:%M', infer_datetime_format=True)
time_ser

0   2015-01-01 00:00:00
1   2016-10-02 00:00:00
2   2018-03-07 00:00:00
3   2014-05-06 00:00:00
4   2016-04-12 00:00:00
5   2019-04-06 11:20:00
dtype: datetime64[ns]

In [ ]:
#28. Write a Pandas program to get the day of month, day of year, week number and day of week from a given series of date strings.

ser3= pd.Series(['01 Jan 2015', '10-02-2016', '20180307', '2014/05/06', '2016-04-12', '2019-04-06T11:20'])

dser = pd.to_datetime(ser3,errors='coerce')

day_month= dser.dt.day.tolist()
day_year= dser.dt.dayofyear.tolist()
week_num= dser.dt.week.tolist()
day_week= dser.dt.day_name().tolist()

print(day_month)
print(day_year)
print(week_num)
print(day_week)

[1, 2, 7, 6, 12, 6]
[1, 276, 66, 126, 103, 96]
[1, 39, 10, 19, 15, 14]
['Thursday', 'Sunday', 'Wednesday', 'Tuesday', 'Tuesday', 'Saturday']


<ipython-input-26-3c08bd18bc78>:9: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated. Please use Series.dt.isocalendar().week instead.
  week_num= dser.dt.week.tolist()


In [ ]:
#29. Write a Pandas program to convert year-month string to dates adding a specified day of the month.

ser4= pd.Series(['Jan 2015', 'Feb 2016', 'Mar 2017', 'Apr 2018', 'May 2019'])

day = 11

new = pd.to_datetime(ser4 + ' ' + str(day),format='%b %Y %d')
new


0   2015-01-11
1   2016-02-11
2   2017-03-11
3   2018-04-11
4   2019-05-11
dtype: datetime64[ns]

In [ ]:
#30. Write a Pandas program to filter words from a given series that contain atleast two vowels.


In [ ]:
#31. Write a Pandas program to compute the Euclidean distance between two given series.

In [ ]:
#32. Write a Pandas program to find the positions of the values neighboured by smaller values on both sides in a given series.

In [ ]:
#35. Write a Pandas program to create a TimeSeries to display all the Sundays of given year

sundays_series = pd.date_range(start=f'2019-01-01', end=f'2019-12-31', freq='W-SUN')

sundays_df = pd.DataFrame({'All Sundays of {}'.format(2019): sundays_series})

print(sundays_df)


   All Sundays of 2019
0           2019-01-06
1           2019-01-13
2           2019-01-20
3           2019-01-27
4           2019-02-03
5           2019-02-10
6           2019-02-17
7           2019-02-24
8           2019-03-03
9           2019-03-10
10          2019-03-17
11          2019-03-24
12          2019-03-31
13          2019-04-07
14          2019-04-14
15          2019-04-21
16          2019-04-28
17          2019-05-05
18          2019-05-12
19          2019-05-19
20          2019-05-26
21          2019-06-02
22          2019-06-09
23          2019-06-16
24          2019-06-23
25          2019-06-30
26          2019-07-07
27          2019-07-14
28          2019-07-21
29          2019-07-28
30          2019-08-04
31          2019-08-11
32          2019-08-18
33          2019-08-25
34          2019-09-01
35          2019-09-08
36          2019-09-15
37          2019-09-22
38          2019-09-29
39          2019-10-06
40          2019-10-13
41          2019-10-20
42         

In [ ]:
#36. Write a Pandas program to convert given series into a dataframe with its index as another column on the dataframe.

ser5= pd.Series(['A','B','C','D','E'])
DF= ser5.reset_index()
DF


index  0
0      0  C
1      1  B
2      2  A
3      3  D
4      4  E

In [ ]:
#37. Write a Pandas program to stack two given series vertically and horizontally.

series1 = pd.Series([1, 2, 3, 4])
series2 = pd.Series(['A', 'B', 'C', 'D'])

hor = pd.concat([series1, series2], axis=0)
ver = pd.concat([series1, series2], axis=1)
print(ver)

   0  1
0  1  A
1  2  B
2  3  C
3  4  D


In [ ]:
#38. Write a Pandas program to check the equality of two given series
series3 = pd.Series([1, 8, 7, 5, 6, 5, 3, 4, 7, 1])
series4 = pd.Series([1, 8, 7, 3, 4, 7, 1, 5, 6, 5])

eq = series3 == series4
print(eq)

0     True
1     True
2     True
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool


In [ ]:
#39. Write a Pandas program to find the index of the first occurrence of the smallest and largest value of a given series.
ser5 = pd.Series([1, 3, 7, 12, 88, 23, 3, 1, 9, 0])
max_ind = ser5.idxmax()
min_ind = ser5.idxmin()

print(max_ind)
print(min_ind)


4
9


In [ ]:
#40. Write a Pandas program to check inequality over the index axis of a given data frame and a given series.
data={'W': [68.0, 75.0, 86.0, 80.0, None],
        'X': [78.0, 75.0, None, 80.0, 86.0],
        'Y': [84, 94, 89, 86, 86],
        'Z': [86, 97, 96, 72, 83]}
df = pd.DataFrame(data)
ser6 = pd.Series([68.0, 75.0, 86.0, 80.0, None])

ineq= df != ser6[:, None]
print(ineq)

       W      X     Y     Z
0  False   True  True  True
1  False  False  True  True
2  False   True  True  True
3  False  False  True  True
4   True   True  True  True


<ipython-input-42-2f7609b4d715>:9: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  ineq= df != ser6[:, None]
